# Site settings
title: Apuntes de eduardofilo
email: hmitsurugi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Apuntes varios sobre algunas de las cosas que necesito recordar,
  principalmente sobre Desarrollo y Sistemas.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eduardofilo.github.io" # the base hostname & protocol for your site
twitter_username: eduardofilo
github_username:  eduardofilo

# Build settings
timezone: Europe/Madrid
locale: es
    
markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript","tables", "with_toc_data"]

#markdown: kramdown

kramdown: 
  input: GFM 
  use_coderay: true
  coderay:
    coderay_line_numbers: true
    coderay_css: class